spring:
  application:
    name: async-boost

  data:
    mongodb:
      uri: mongodb://${DB_SERVER}/asyncboostdb
      authentication-database: admin
      username: ${DB_SERVER_USERNAME}
      password: ${DB_SERVER_PASSWORD}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER}
      group-id: chat-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 500
      auto-commit-interval: 1000
    producer:
      bootstrap-servers: ${KAFKA_SERVER}
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
      concurrency: 3
