spring:
  application:
    name: async-boost

  data:
    mongodb:
      uri: mongodb://${DB_SERVER}/asyncboostdb
      authentication-database: admin
      username: ${DB_SERVER_USERNAME}
      password: ${DB_SERVER_PASSWORD}
